# Generated by Django 4.2.7 on 2023-12-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField()),
                ('stock', models.BooleanField(default=True)),
                ('referencia', models.CharField(max_length=20)),
            ],
        ),
    ]
