# Generated by Django 4.2.7 on 2023-12-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField()),
                ('puntuacion', models.FloatField()),
                ('juego_id', models.PositiveIntegerField()),
                ('juego_nombre', models.TextField()),
            ],
        ),
    ]
